### ISSUE TITLE
SWT Invalid thread access on macOS

### ISSUE THREAD

**Issue by robertbio** [geckoprojects-org/org.gecko.bnd.eclipse#4]
```
# framework=org.eclipse.osgi.launch.Equinox@1ab3a8c8
# setting launcher service registration to launcher.ready=true
# will wait for a registered Runnable
***WARNING: Display must be created on main thread due to Cocoa restrictions. Use vmarg -XstartOnFirstThread
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4907)
	at org.eclipse.swt.SWT.error(SWT.java:4822)
	at org.eclipse.swt.SWT.error(SWT.java:4793)
	at org.eclipse.swt.widgets.Display.error(Display.java:1148)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:899)
	at org.eclipse.swt.widgets.Display.create(Display.java:883)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:131)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:739)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:730)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:1482)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.getApplicationDisplay(E4Application.java:137)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.gecko.eclipse.compatibility.EclipsePlatformStarter.lambda$startApplication$0(EclipsePlatformStarter.java:183)
	at org.osgi.util.promise.DeferredPromiseImpl$Submit.run(DeferredPromiseImpl.java:658)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

The vmarg `-XstartOnFirstThread` is added.

<img width="1273" alt="Screen Shot 2022-04-08 at 12 10 23 PM" src="https://user-images.githubusercontent.com/4689476/162415181-778d5c7b-43ad-48c9-9099-7dc6369548c5.png">

**Comment by juergen-albert** [comment]
The issue is fixed and Version 1.2.1-SNAPSHOT is available on [https://oss.sonatype.org/content/repositories/snapshots/](https://oss.sonatype.org/content/repositories/snapshots). I will do a release when https://github.com/bndtools/bnd/pull/5205 is done.

**Comment by juergen-albert** [comment]
I'll leave the issue open till then.
